### ISSUE TITLE
RuntimeError: expected device cuda:0 but got device cpu

### ISSUE THREAD

**Issue by haosirong** [Lyken17/pytorch-OpCounter#101]
I test my own model.

import torch
import torch.nn as nn                   
from torchsummary import summary
from thop import profile                

class CSDN_Tem(nn.Module):              
    def __init__(self, in_ch, out_ch):  
        super(CSDN_Tem, self).__init__()
        self.depth_conv = nn.Conv2d(in_channels=in_ch,out_channels=in_ch,kernel_size=3,stride=1,padding=1,groups=in_ch)
        self.point_conv = nn.Conv2d(in_channels=in_ch,out_channels=out_ch,kernel_size=1,stride=1,padding=0,groups=1)

    def forward(self, input):
        print(input.size())
        out = self.depth_conv(input)
        out = self.point_conv(out)
        print(out.size())
        return out

torch.set_default_tensor_type(torch.cuda.FloatTensor)

conv = CSDN_Tem(8, 32)
#print(summary(conv, (8,128, 128), batch_size=1))

flops, params = profile(conv, inputs=(torch.randn(1,8,128,128),))

-------------------------------
And would report

(base) test1@air:~/pytorch/test$ python disp_model.py 
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[WARN] Cannot find rule for <class '__main__.CSDN_Tem'>. Treat it as zero Macs and zero Params.
torch.Size([1, 8, 128, 128])
Traceback (most recent call last):
  File "disp_model.py", line 24, in <module>
    flops, params = profile(conv, inputs=(torch.randn(1,8,128,128),))
  File "/home/test1/miniconda3/lib/python3.7/site-packages/thop/profile.py", line 188, in profile
    model(*inputs)
  File "/home/test1/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "disp_model.py", line 14, in forward
    out = self.depth_conv(input)
  File "/home/test1/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in __call__
    hook_result = hook(self, input, result)
  File "/home/test1/miniconda3/lib/python3.7/site-packages/thop/vision/basic_hooks.py", line 31, in count_convNd
    m.total_ops += torch.DoubleTensor([int(total_ops)])
RuntimeError: expected device cuda:0 but got device cpu

---------------------------------------
Wonder know how to resovle this, Thks

**Comment by Lyken17** [comment]
The code format breaks. Please fix it so I can know what your code is.
