### ISSUE TITLE
Google Colab Incompatibility with YOLOv5

### ISSUE THREAD

**Issue by glenn-jocher** [Lyken17/pytorch-OpCounter#113]
Hi there! We use the super useful thop package in YOLOv5, and it works great, except that when we install it in Google Colab we receive an error when using it with GPU (CPU works well).
<a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>

We only use thop if we detect the package installed, so you can reproduce this error easily at the official YOLOv5 notebook by running the first two cells (Setup and Detect), and then restarting the runtime, `pip install thop` after Setup, and then run Detect.

Normal result:
<img width="1259" alt="Screenshot 2020-11-14 at 14 25 24" src="https://user-images.githubusercontent.com/26833433/99148149-71b39600-2686-11eb-8915-ddd1c19ea1bf.png">

Google Colab result on GPU:
<img width="1437" alt="Screenshot 2020-11-14 at 14 35 31" src="https://user-images.githubusercontent.com/26833433/99148184-aa536f80-2686-11eb-89db-263603284a26.png">

Error message is:
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='data/images/', update=False, view_img=False, weights=['yolov5s.pt'])
Using torch 1.7.0+cu101 CUDA:0 (Tesla V100-SXM2-16GB, 16130MB)

Fusing layers... 
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/content/yolov5/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/content/yolov5/yolov5/models/yolo.py", line 172, in fuse
    self.info()
  File "/content/yolov5/yolov5/models/yolo.py", line 196, in info
    model_info(self, verbose)
  File "/content/yolov5/yolov5/utils/torch_utils.py", line 155, in model_info
    flops = profile(deepcopy(model), inputs=(torch.zeros(1, 3, 64, 64),), verbose=False)[0] / 1E9 * 2
  File "/usr/local/lib/python3.6/dist-packages/thop/profile.py", line 188, in profile
    model(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/yolov5/models/yolo.py", line 121, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/content/yolov5/yolov5/models/yolo.py", line 137, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/yolov5/models/common.py", line 93, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/yolov5/yolov5/models/common.py", line 37, in fuseforward
    return self.act(self.conv(x))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
```

Any idea why this is happening? Any help would be greatly appreciated, thanks!!

**Comment by Lyken17** [comment]
`Expected object of device type cuda but got device type cpu for argument #1 `

Did you turn on GPU options in Colab? If you use GPU, then the input data should also be a GPU tensor.
