### ISSUE TITLE
error run evaluate_famous_models.py

### ISSUE THREAD

**Issue by Scriabing** [Lyken17/pytorch-OpCounter#94]
I keep thop upgrade,but `python evaluate_famous_models.py`
terminal return:
Model | Params(M) | FLOPs(G)
---|---|---
alexnet | 61.10 | 0.71

`
Traceback (most recent call last):
  File "evaluate_famous_models.py", line 17, in <module>
    model = models.__dict__[name]().to(device)
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/site-packages/torchvision/models/densenet.py", line 25, in densenet121
    model = DenseNet(num_init_features=64, growth_rate=32, block_config=(6, 12, 24, 16))
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/site-packages/torchvision/models/densenet.py", line 138, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/site-packages/torchvision/models/densenet.py", line 94, in __init__
    layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/site-packages/torchvision/models/densenet.py", line 73, in __init__
    self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/site-packages/torch/nn/modules/module.py", line 196, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'
`
actually,i run evaluate_runs_models.py  and the instance from 'https://github.com/Lyken17/pytorch-OpCounter'/issues/69 sucessfully. My pytorch version is 1.5.1

**Comment by Lyken17** [comment]
Under my enviornment, `python evaluate_famous_models.py` yields no error. Please attach your version of `thop`, `torchvision` as well, so I can better reproduce.
