### ISSUE TITLE
MACs value becomes too large if there are shared modules

### ISSUE THREAD

**Issue by sile** [Lyken17/pytorch-OpCounter#98]
I think that the calculated MACs value becomes too large if there are shared modules.
The following is a script to reproduce this issue.
```python
from thop import profile
import torch
from torch import nn

class Net(nn.Module):
    def __init__(self, repeat=1):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        return self.linear(x)

def create_modules(share):
    m0 = Net()
    m1 = Net()
    m = nn.Sequential(m0, m1)
    if share:
        m1.linear = m0.linear
    return m

def measure(share):
    macs, params = profile(create_modules(share=share), (torch.randn(1, 10),))
    print("[share={}] macs={}, params={}".format(share, macs, params))

measure(True)
measure(False)
```

The execution result is shown below:
```console
$ python3 test.py
[share=True] macs=800.0, params=220.0
[share=False] macs=200.0, params=220.0
```

If `m0` and `m1` share the linear module, the MACs value is 800 but it should be the same as the non shared version (i.e., 200).

**Comment by Lyken17** [comment]
THOP does the repeative because some recurrent modules require it. For example

```python
class Net(nn.Module):
    def __init__(self, repeat=1):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        x = self.linear(x)
        x = self.linear(x)
        x = self.linear(x)
       return x
```

In that case, the `linear` is indeed called 3 times and should be counted 3 times as well. I think a better way to address you problem is `net.clone()` before profiling it.

**Comment by sile** [comment]
Thank you for your response and for letting me know the workaround (`net.clone()`).
But, I think, the patch #99 I created can handle the above recurrent module case as the same as the current master branch. 
Please let me know if I'm wrong.

**Comment by sile** [comment]
Hmm, I tried modifying my example code to call `net.clone()` before passing the module to `profile` function as follows:

```python
from thop import profile
import torch
from torch import nn

class Net(nn.Module):
    def __init__(self, repeat=1):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        return self.linear(x)

def create_modules(share):
    m0 = Net()
    m1 = Net()
    m = nn.Sequential(m0, m1)
    if share:
        m1.linear = m0.linear
    return m

def measure(share):
    macs, params = profile(create_modules(share=share).clone(), (torch.randn(1, 10),))
    print(macs, params)

measure(True)
measure(False)
```

However, the following error message was raised when I executed the script:
```python
$ python3 thop-issue98.py
Traceback (most recent call last):
  File "/tmp/thop-test.py", line 29, in <module>
    measure(True)
  File "/tmp/thop-test.py", line 25, in measure
    macs, params = profile(create_modules(share=share).clone(), (torch.randn(1, 10),))
  File "/home/ohta/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'clone'
```

Sorry for bothering you, but please let me know if you have any idea to fix the error.

**Comment by Lyken17** [comment]
Can you try `copy.deepcopy(model)`?

**Comment by sile** [comment]
Thanks. When I replaced `create_modules(share=share).clone()` with `copy.deepcopy(create_modules(share=share))`, the script ran without error. However the profiling result didn't differ between with/without `copy.deepcopy` invocation.

**Comment by wyf0912** [comment]
```python
In [16]: class UnShared(nn.Module):
    ...:     def __init__(self):
    ...:         super().__init__()
    ...:         self.l = nn.Linear(10,10)
    ...:         self.l2=nn.Linear(10,10)
    ...:     def forward(self,x):
    ...:         return self.l(x)+self.l2(x)
    ...: 

In [17]: class Shared(nn.Module):
    ...:     def __init__(self):
    ...:         super().__init__()
    ...:         self.l = nn.Linear(10,10)
    ...:         self.l2=nn.Linear(10,10)
    ...:     def forward(self,x):
    ...:         return self.l(x)+self.l(x)
    ...: 
```
```
In [18]: profile(Shared(), (torch.randn(1,10),))
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class '__main__.Shared'>. Treat it as zero Macs and zero Params.
Out[18]: (200.0, 110.0)

In [19]: profile(UnShared(), (torch.randn(1,10),))
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class '__main__.UnShared'>. Treat it as zero Macs and zero Params.
Out[19]: (200.0, 220.0)
```
Hi, It seems my examples are correct.
